// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oociyoccgjtjdtripnoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vY2l5b2NjZ2p0amR0cmlwbm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTA5NTgsImV4cCI6MjA1OTA4Njk1OH0.g0O8uqntKzPNMW7wTzfBjBG2a9RlxWAOkeq2S2nscJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);